"""Extract a solved guard-mutation attack path from a native UI export."""

import argparse
from pathlib import Path
import re
import sys
import tempfile

from mutation import OPTIONS, TARGETS, check_outcome, check_toolchain
from replay import ReplayError, export_parts, run


def extract_attack(source: str, target: str) -> tuple[str, str]:
    prefix, blocks = export_parts(source)
    if target not in blocks:
        raise ReplayError(f"missing {target}")
    lines = blocks[target].splitlines(keepends=True)
    if sum(bool(re.match(r"\s*SOLVED\b", line)) for line in lines) != 1:
        raise ReplayError("expected exactly one native solved attack path")
    removed = set()
    for index, line in enumerate(lines):
        case = re.match(r"([ \t]*)case ", line)
        if not case:
            continue
        end = index + 1
        while end < len(lines):
            boundary = re.match(r"([ \t]*)(?:next|qed)\s*$", lines[end])
            if boundary and len(boundary[1]) < len(case[1]):
                break
            end += 1
        if not any(re.match(r"\s*SOLVED\b", entry) for entry in lines[index:end]):
            removed.update(range(index, end))
    certificate = "".join(
        line for index, line in enumerate(lines)
        if index not in removed and not re.match(r"\s*next\s*$", line)
    )
    if re.search(r"\b(?:sorry|admit)\b", certificate):
        raise ReplayError("attack path contains unfinished steps")
    return prefix, certificate


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="native saved theory with one solved target path")
    parser.add_argument("--mutation", choices=tuple(TARGETS), default="CLASSIC_FALLBACK")
    parser.add_argument("--output", type=Path)
    arguments = parser.parse_args()
    try:
        check_toolchain()
        target = TARGETS[arguments.mutation]
        prefix, certificate = extract_attack(arguments.source.read_text(), target)
        with tempfile.TemporaryDirectory(prefix="cairn-attack-extract-") as temporary:
            theory = Path(temporary) / "attack.spthy"
            theory.write_text(prefix + certificate + "end\n")
            output = run(["tamarin-prover", str(theory), *OPTIONS], 180)
            check_outcome(output, "falsified", target)
        output_path = arguments.output or Path(__file__).resolve().with_name(
            f"ratchet-{arguments.mutation.lower().replace('_', '-')}-attack.inc",
        )
        output_path.write_text(
            "/* Generated by extract_attack.py from a native Tamarin 1.12.0 attack export. */\n\n"
            + certificate,
        )
        print(f"Saved replayed attack certificate: {output_path}")
        return 0
    except (OSError, ReplayError) as error:
        print(f"FAIL: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
